compile:
	g++ Date.cpp PizzaWars.cpp PizzaStore.cpp -Wall -c
	g++ driver.cpp Date.o PizzaWars.o PizzaStore.o MysteryMachine.o -o battle.out -Wall
run:
	./battle.out
clean:
	rm *.exe
date:
	g++ Date.cpp -Wall -c
pizza:
	g++ PizzaWars.cpp -Wall -c
store:
	g++ PizzaStore.cpp -Wall -c
editDriver:
	vim driver.cpp
editDate:
	vim Date.cpp
editPizza:
	vim PizzaWars.cpp
